"""Corrigiendo columna datos_generales en formulario_base

Revision ID: 25c4e155f86b
Revises: 1fc14b667a26
Create Date: 2025-02-18 17:15:56.126929

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '25c4e155f86b'
down_revision = '1fc14b667a26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('respuesta_campo_dinamico')
    with op.batch_alter_table('formulario_base', schema=None) as batch_op:
        batch_op.alter_column('datos_generales',
               existing_type=sqlite.JSON(),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('estado',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('formulario_base', schema=None) as batch_op:
        batch_op.alter_column('estado',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('datos_generales',
               existing_type=sa.Text(),
               type_=sqlite.JSON(),
               existing_nullable=False)

    op.create_table('respuesta_campo_dinamico',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('formulario_id', sa.INTEGER(), nullable=False),
    sa.Column('campo_id', sa.INTEGER(), nullable=False),
    sa.Column('valor', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['campo_id'], ['campo_formulario.id'], ),
    sa.ForeignKeyConstraint(['formulario_id'], ['formulario_base.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
